/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RmaApproveReturnRequestItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RmaApproveReturnRequest
 */
public class RmaApproveReturnRequestTest {
    private final RmaApproveReturnRequest model = new RmaApproveReturnRequest();

    /**
     * Model tests for RmaApproveReturnRequest
     */
    @Test
    public void testRmaApproveReturnRequest() {
        // TODO: test RmaApproveReturnRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'refundShippingCost'
     */
    @Test
    public void refundShippingCostTest() {
        // TODO: test refundShippingCost
    }

    /**
     * Test the property 'refundPaymentCost'
     */
    @Test
    public void refundPaymentCostTest() {
        // TODO: test refundPaymentCost
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
