/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RmaListNotesByReturnIdRequestSortSortField;
import org.openapitools.client.model.RmaSortOrder;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RmaListNotesByReturnIdRequestSort
 */
public class RmaListNotesByReturnIdRequestSortTest {
    private final RmaListNotesByReturnIdRequestSort model = new RmaListNotesByReturnIdRequestSort();

    /**
     * Model tests for RmaListNotesByReturnIdRequestSort
     */
    @Test
    public void testRmaListNotesByReturnIdRequestSort() {
        // TODO: test RmaListNotesByReturnIdRequestSort
    }

    /**
     * Test the property 'evaluationOrder'
     */
    @Test
    public void evaluationOrderTest() {
        // TODO: test evaluationOrder
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
