/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RmaMoney;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RmaOrderDataItem
 */
public class RmaOrderDataItemTest {
    private final RmaOrderDataItem model = new RmaOrderDataItem();

    /**
     * Model tests for RmaOrderDataItem
     */
    @Test
    public void testRmaOrderDataItem() {
        // TODO: test RmaOrderDataItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'productGrn'
     */
    @Test
    public void productGrnTest() {
        // TODO: test productGrn
    }

    /**
     * Test the property 'qtyOrdered'
     */
    @Test
    public void qtyOrderedTest() {
        // TODO: test qtyOrdered
    }

    /**
     * Test the property 'qtyCommitted'
     */
    @Test
    public void qtyCommittedTest() {
        // TODO: test qtyCommitted
    }

    /**
     * Test the property 'qtyShipped'
     */
    @Test
    public void qtyShippedTest() {
        // TODO: test qtyShipped
    }

    /**
     * Test the property 'unitSalePrice'
     */
    @Test
    public void unitSalePriceTest() {
        // TODO: test unitSalePrice
    }

    /**
     * Test the property 'unitListPrice'
     */
    @Test
    public void unitListPriceTest() {
        // TODO: test unitListPrice
    }

    /**
     * Test the property 'unitVatAmount'
     */
    @Test
    public void unitVatAmountTest() {
        // TODO: test unitVatAmount
    }

    /**
     * Test the property 'rowSalePrice'
     */
    @Test
    public void rowSalePriceTest() {
        // TODO: test rowSalePrice
    }

    /**
     * Test the property 'rowListPrice'
     */
    @Test
    public void rowListPriceTest() {
        // TODO: test rowListPrice
    }

    /**
     * Test the property 'rowVatAmount'
     */
    @Test
    public void rowVatAmountTest() {
        // TODO: test rowVatAmount
    }

    /**
     * Test the property 'vatPercentage'
     */
    @Test
    public void vatPercentageTest() {
        // TODO: test vatPercentage
    }

    /**
     * Test the property 'vatInaccurate'
     */
    @Test
    public void vatInaccurateTest() {
        // TODO: test vatInaccurate
    }

    /**
     * Test the property 'vatCalculated'
     */
    @Test
    public void vatCalculatedTest() {
        // TODO: test vatCalculated
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'productSku'
     */
    @Test
    public void productSkuTest() {
        // TODO: test productSku
    }

    /**
     * Test the property 'productOptions'
     */
    @Test
    public void productOptionsTest() {
        // TODO: test productOptions
    }

    /**
     * Test the property 'productImg'
     */
    @Test
    public void productImgTest() {
        // TODO: test productImg
    }

    /**
     * Test the property 'productData'
     */
    @Test
    public void productDataTest() {
        // TODO: test productData
    }

    /**
     * Test the property 'shipmentInfoReference'
     */
    @Test
    public void shipmentInfoReferenceTest() {
        // TODO: test shipmentInfoReference
    }

    /**
     * Test the property 'promotionGrn'
     */
    @Test
    public void promotionGrnTest() {
        // TODO: test promotionGrn
    }

    /**
     * Test the property 'productIsVirtual'
     */
    @Test
    public void productIsVirtualTest() {
        // TODO: test productIsVirtual
    }

}
