/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RmaPostalAddress
 */
public class RmaPostalAddressTest {
    private final RmaPostalAddress model = new RmaPostalAddress();

    /**
     * Model tests for RmaPostalAddress
     */
    @Test
    public void testRmaPostalAddress() {
        // TODO: test RmaPostalAddress
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'regionCode'
     */
    @Test
    public void regionCodeTest() {
        // TODO: test regionCode
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'sortingCode'
     */
    @Test
    public void sortingCodeTest() {
        // TODO: test sortingCode
    }

    /**
     * Test the property 'administrativeArea'
     */
    @Test
    public void administrativeAreaTest() {
        // TODO: test administrativeArea
    }

    /**
     * Test the property 'locality'
     */
    @Test
    public void localityTest() {
        // TODO: test locality
    }

    /**
     * Test the property 'sublocality'
     */
    @Test
    public void sublocalityTest() {
        // TODO: test sublocality
    }

    /**
     * Test the property 'addressLines'
     */
    @Test
    public void addressLinesTest() {
        // TODO: test addressLines
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

}
