/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RmaCustomerInfo;
import org.openapitools.client.model.RmaOrderData;
import org.openapitools.client.model.RmaPostalAddress;
import org.openapitools.client.model.RmaRefundMethod;
import org.openapitools.client.model.RmaReturnHistory;
import org.openapitools.client.model.RmaReturnProduct;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RmaReturnResponse
 */
public class RmaReturnResponseTest {
    private final RmaReturnResponse model = new RmaReturnResponse();

    /**
     * Model tests for RmaReturnResponse
     */
    @Test
    public void testRmaReturnResponse() {
        // TODO: test RmaReturnResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'grn'
     */
    @Test
    public void grnTest() {
        // TODO: test grn
    }

    /**
     * Test the property 'orderGrn'
     */
    @Test
    public void orderGrnTest() {
        // TODO: test orderGrn
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

    /**
     * Test the property 'preferredRefundMethod'
     */
    @Test
    public void preferredRefundMethodTest() {
        // TODO: test preferredRefundMethod
    }

    /**
     * Test the property 'refundShippingCost'
     */
    @Test
    public void refundShippingCostTest() {
        // TODO: test refundShippingCost
    }

    /**
     * Test the property 'refundPaymentCost'
     */
    @Test
    public void refundPaymentCostTest() {
        // TODO: test refundPaymentCost
    }

    /**
     * Test the property 'customerInfo'
     */
    @Test
    public void customerInfoTest() {
        // TODO: test customerInfo
    }

    /**
     * Test the property 'returnAddress'
     */
    @Test
    public void returnAddressTest() {
        // TODO: test returnAddress
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'history'
     */
    @Test
    public void historyTest() {
        // TODO: test history
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'orderData'
     */
    @Test
    public void orderDataTest() {
        // TODO: test orderData
    }

}
