/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RmaMoney;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.Rma.JSON;

/**
 * RmaOrderDataItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-15T16:29:20.741881326Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class RmaOrderDataItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PRODUCT_GRN = "productGrn";
  @SerializedName(SERIALIZED_NAME_PRODUCT_GRN)
  private String productGrn;

  public static final String SERIALIZED_NAME_QTY_ORDERED = "qtyOrdered";
  @SerializedName(SERIALIZED_NAME_QTY_ORDERED)
  private Long qtyOrdered;

  public static final String SERIALIZED_NAME_QTY_COMMITTED = "qtyCommitted";
  @SerializedName(SERIALIZED_NAME_QTY_COMMITTED)
  private Long qtyCommitted;

  public static final String SERIALIZED_NAME_QTY_SHIPPED = "qtyShipped";
  @SerializedName(SERIALIZED_NAME_QTY_SHIPPED)
  private Long qtyShipped;

  public static final String SERIALIZED_NAME_UNIT_SALE_PRICE = "unitSalePrice";
  @SerializedName(SERIALIZED_NAME_UNIT_SALE_PRICE)
  private RmaMoney unitSalePrice;

  public static final String SERIALIZED_NAME_UNIT_LIST_PRICE = "unitListPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_LIST_PRICE)
  private RmaMoney unitListPrice;

  public static final String SERIALIZED_NAME_UNIT_VAT_AMOUNT = "unitVatAmount";
  @SerializedName(SERIALIZED_NAME_UNIT_VAT_AMOUNT)
  private RmaMoney unitVatAmount;

  public static final String SERIALIZED_NAME_ROW_SALE_PRICE = "rowSalePrice";
  @SerializedName(SERIALIZED_NAME_ROW_SALE_PRICE)
  private RmaMoney rowSalePrice;

  public static final String SERIALIZED_NAME_ROW_LIST_PRICE = "rowListPrice";
  @SerializedName(SERIALIZED_NAME_ROW_LIST_PRICE)
  private RmaMoney rowListPrice;

  public static final String SERIALIZED_NAME_ROW_VAT_AMOUNT = "rowVatAmount";
  @SerializedName(SERIALIZED_NAME_ROW_VAT_AMOUNT)
  private RmaMoney rowVatAmount;

  public static final String SERIALIZED_NAME_VAT_PERCENTAGE = "vatPercentage";
  @SerializedName(SERIALIZED_NAME_VAT_PERCENTAGE)
  private Float vatPercentage;

  public static final String SERIALIZED_NAME_VAT_INACCURATE = "vatInaccurate";
  @SerializedName(SERIALIZED_NAME_VAT_INACCURATE)
  private Boolean vatInaccurate;

  public static final String SERIALIZED_NAME_VAT_CALCULATED = "vatCalculated";
  @SerializedName(SERIALIZED_NAME_VAT_CALCULATED)
  private Boolean vatCalculated;

  public static final String SERIALIZED_NAME_PRODUCT_NAME = "productName";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NAME)
  private String productName;

  public static final String SERIALIZED_NAME_PRODUCT_CODE = "productCode";
  @SerializedName(SERIALIZED_NAME_PRODUCT_CODE)
  private String productCode;

  public static final String SERIALIZED_NAME_PRODUCT_SKU = "productSku";
  @SerializedName(SERIALIZED_NAME_PRODUCT_SKU)
  private String productSku;

  public static final String SERIALIZED_NAME_PRODUCT_OPTIONS = "productOptions";
  @SerializedName(SERIALIZED_NAME_PRODUCT_OPTIONS)
  private String productOptions;

  public static final String SERIALIZED_NAME_PRODUCT_IMG = "productImg";
  @SerializedName(SERIALIZED_NAME_PRODUCT_IMG)
  private String productImg;

  public static final String SERIALIZED_NAME_PRODUCT_DATA = "productData";
  @SerializedName(SERIALIZED_NAME_PRODUCT_DATA)
  private String productData;

  public static final String SERIALIZED_NAME_SHIPMENT_INFO_REFERENCE = "shipmentInfoReference";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_INFO_REFERENCE)
  private String shipmentInfoReference;

  public static final String SERIALIZED_NAME_PROMOTION_GRN = "promotionGrn";
  @SerializedName(SERIALIZED_NAME_PROMOTION_GRN)
  private List<String> promotionGrn = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRODUCT_IS_VIRTUAL = "productIsVirtual";
  @SerializedName(SERIALIZED_NAME_PRODUCT_IS_VIRTUAL)
  private Boolean productIsVirtual;

  public RmaOrderDataItem() {
  }

  public RmaOrderDataItem id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public RmaOrderDataItem productGrn(String productGrn) {
    this.productGrn = productGrn;
    return this;
  }

  /**
   * Get productGrn
   * @return productGrn
   */
  @javax.annotation.Nullable
  public String getProductGrn() {
    return productGrn;
  }

  public void setProductGrn(String productGrn) {
    this.productGrn = productGrn;
  }


  public RmaOrderDataItem qtyOrdered(Long qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
    return this;
  }

  /**
   * Get qtyOrdered
   * @return qtyOrdered
   */
  @javax.annotation.Nullable
  public Long getQtyOrdered() {
    return qtyOrdered;
  }

  public void setQtyOrdered(Long qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
  }


  public RmaOrderDataItem qtyCommitted(Long qtyCommitted) {
    this.qtyCommitted = qtyCommitted;
    return this;
  }

  /**
   * Get qtyCommitted
   * @return qtyCommitted
   */
  @javax.annotation.Nullable
  public Long getQtyCommitted() {
    return qtyCommitted;
  }

  public void setQtyCommitted(Long qtyCommitted) {
    this.qtyCommitted = qtyCommitted;
  }


  public RmaOrderDataItem qtyShipped(Long qtyShipped) {
    this.qtyShipped = qtyShipped;
    return this;
  }

  /**
   * Get qtyShipped
   * @return qtyShipped
   */
  @javax.annotation.Nullable
  public Long getQtyShipped() {
    return qtyShipped;
  }

  public void setQtyShipped(Long qtyShipped) {
    this.qtyShipped = qtyShipped;
  }


  public RmaOrderDataItem unitSalePrice(RmaMoney unitSalePrice) {
    this.unitSalePrice = unitSalePrice;
    return this;
  }

  /**
   * Get unitSalePrice
   * @return unitSalePrice
   */
  @javax.annotation.Nullable
  public RmaMoney getUnitSalePrice() {
    return unitSalePrice;
  }

  public void setUnitSalePrice(RmaMoney unitSalePrice) {
    this.unitSalePrice = unitSalePrice;
  }


  public RmaOrderDataItem unitListPrice(RmaMoney unitListPrice) {
    this.unitListPrice = unitListPrice;
    return this;
  }

  /**
   * Get unitListPrice
   * @return unitListPrice
   */
  @javax.annotation.Nullable
  public RmaMoney getUnitListPrice() {
    return unitListPrice;
  }

  public void setUnitListPrice(RmaMoney unitListPrice) {
    this.unitListPrice = unitListPrice;
  }


  public RmaOrderDataItem unitVatAmount(RmaMoney unitVatAmount) {
    this.unitVatAmount = unitVatAmount;
    return this;
  }

  /**
   * Get unitVatAmount
   * @return unitVatAmount
   */
  @javax.annotation.Nullable
  public RmaMoney getUnitVatAmount() {
    return unitVatAmount;
  }

  public void setUnitVatAmount(RmaMoney unitVatAmount) {
    this.unitVatAmount = unitVatAmount;
  }


  public RmaOrderDataItem rowSalePrice(RmaMoney rowSalePrice) {
    this.rowSalePrice = rowSalePrice;
    return this;
  }

  /**
   * Get rowSalePrice
   * @return rowSalePrice
   */
  @javax.annotation.Nullable
  public RmaMoney getRowSalePrice() {
    return rowSalePrice;
  }

  public void setRowSalePrice(RmaMoney rowSalePrice) {
    this.rowSalePrice = rowSalePrice;
  }


  public RmaOrderDataItem rowListPrice(RmaMoney rowListPrice) {
    this.rowListPrice = rowListPrice;
    return this;
  }

  /**
   * Get rowListPrice
   * @return rowListPrice
   */
  @javax.annotation.Nullable
  public RmaMoney getRowListPrice() {
    return rowListPrice;
  }

  public void setRowListPrice(RmaMoney rowListPrice) {
    this.rowListPrice = rowListPrice;
  }


  public RmaOrderDataItem rowVatAmount(RmaMoney rowVatAmount) {
    this.rowVatAmount = rowVatAmount;
    return this;
  }

  /**
   * Get rowVatAmount
   * @return rowVatAmount
   */
  @javax.annotation.Nullable
  public RmaMoney getRowVatAmount() {
    return rowVatAmount;
  }

  public void setRowVatAmount(RmaMoney rowVatAmount) {
    this.rowVatAmount = rowVatAmount;
  }


  public RmaOrderDataItem vatPercentage(Float vatPercentage) {
    this.vatPercentage = vatPercentage;
    return this;
  }

  /**
   * Get vatPercentage
   * @return vatPercentage
   */
  @javax.annotation.Nullable
  public Float getVatPercentage() {
    return vatPercentage;
  }

  public void setVatPercentage(Float vatPercentage) {
    this.vatPercentage = vatPercentage;
  }


  public RmaOrderDataItem vatInaccurate(Boolean vatInaccurate) {
    this.vatInaccurate = vatInaccurate;
    return this;
  }

  /**
   * Get vatInaccurate
   * @return vatInaccurate
   */
  @javax.annotation.Nullable
  public Boolean getVatInaccurate() {
    return vatInaccurate;
  }

  public void setVatInaccurate(Boolean vatInaccurate) {
    this.vatInaccurate = vatInaccurate;
  }


  public RmaOrderDataItem vatCalculated(Boolean vatCalculated) {
    this.vatCalculated = vatCalculated;
    return this;
  }

  /**
   * Get vatCalculated
   * @return vatCalculated
   */
  @javax.annotation.Nullable
  public Boolean getVatCalculated() {
    return vatCalculated;
  }

  public void setVatCalculated(Boolean vatCalculated) {
    this.vatCalculated = vatCalculated;
  }


  public RmaOrderDataItem productName(String productName) {
    this.productName = productName;
    return this;
  }

  /**
   * Get productName
   * @return productName
   */
  @javax.annotation.Nullable
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }


  public RmaOrderDataItem productCode(String productCode) {
    this.productCode = productCode;
    return this;
  }

  /**
   * Get productCode
   * @return productCode
   */
  @javax.annotation.Nullable
  public String getProductCode() {
    return productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  public RmaOrderDataItem productSku(String productSku) {
    this.productSku = productSku;
    return this;
  }

  /**
   * Get productSku
   * @return productSku
   */
  @javax.annotation.Nullable
  public String getProductSku() {
    return productSku;
  }

  public void setProductSku(String productSku) {
    this.productSku = productSku;
  }


  public RmaOrderDataItem productOptions(String productOptions) {
    this.productOptions = productOptions;
    return this;
  }

  /**
   * Get productOptions
   * @return productOptions
   */
  @javax.annotation.Nullable
  public String getProductOptions() {
    return productOptions;
  }

  public void setProductOptions(String productOptions) {
    this.productOptions = productOptions;
  }


  public RmaOrderDataItem productImg(String productImg) {
    this.productImg = productImg;
    return this;
  }

  /**
   * Get productImg
   * @return productImg
   */
  @javax.annotation.Nullable
  public String getProductImg() {
    return productImg;
  }

  public void setProductImg(String productImg) {
    this.productImg = productImg;
  }


  public RmaOrderDataItem productData(String productData) {
    this.productData = productData;
    return this;
  }

  /**
   * Get productData
   * @return productData
   */
  @javax.annotation.Nullable
  public String getProductData() {
    return productData;
  }

  public void setProductData(String productData) {
    this.productData = productData;
  }


  public RmaOrderDataItem shipmentInfoReference(String shipmentInfoReference) {
    this.shipmentInfoReference = shipmentInfoReference;
    return this;
  }

  /**
   * Get shipmentInfoReference
   * @return shipmentInfoReference
   */
  @javax.annotation.Nullable
  public String getShipmentInfoReference() {
    return shipmentInfoReference;
  }

  public void setShipmentInfoReference(String shipmentInfoReference) {
    this.shipmentInfoReference = shipmentInfoReference;
  }


  public RmaOrderDataItem promotionGrn(List<String> promotionGrn) {
    this.promotionGrn = promotionGrn;
    return this;
  }

  public RmaOrderDataItem addPromotionGrnItem(String promotionGrnItem) {
    if (this.promotionGrn == null) {
      this.promotionGrn = new ArrayList<>();
    }
    this.promotionGrn.add(promotionGrnItem);
    return this;
  }

  /**
   * Get promotionGrn
   * @return promotionGrn
   */
  @javax.annotation.Nullable
  public List<String> getPromotionGrn() {
    return promotionGrn;
  }

  public void setPromotionGrn(List<String> promotionGrn) {
    this.promotionGrn = promotionGrn;
  }


  public RmaOrderDataItem productIsVirtual(Boolean productIsVirtual) {
    this.productIsVirtual = productIsVirtual;
    return this;
  }

  /**
   * Get productIsVirtual
   * @return productIsVirtual
   */
  @javax.annotation.Nullable
  public Boolean getProductIsVirtual() {
    return productIsVirtual;
  }

  public void setProductIsVirtual(Boolean productIsVirtual) {
    this.productIsVirtual = productIsVirtual;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RmaOrderDataItem instance itself
   */
  public RmaOrderDataItem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RmaOrderDataItem rmaOrderDataItem = (RmaOrderDataItem) o;
    return Objects.equals(this.id, rmaOrderDataItem.id) &&
        Objects.equals(this.productGrn, rmaOrderDataItem.productGrn) &&
        Objects.equals(this.qtyOrdered, rmaOrderDataItem.qtyOrdered) &&
        Objects.equals(this.qtyCommitted, rmaOrderDataItem.qtyCommitted) &&
        Objects.equals(this.qtyShipped, rmaOrderDataItem.qtyShipped) &&
        Objects.equals(this.unitSalePrice, rmaOrderDataItem.unitSalePrice) &&
        Objects.equals(this.unitListPrice, rmaOrderDataItem.unitListPrice) &&
        Objects.equals(this.unitVatAmount, rmaOrderDataItem.unitVatAmount) &&
        Objects.equals(this.rowSalePrice, rmaOrderDataItem.rowSalePrice) &&
        Objects.equals(this.rowListPrice, rmaOrderDataItem.rowListPrice) &&
        Objects.equals(this.rowVatAmount, rmaOrderDataItem.rowVatAmount) &&
        Objects.equals(this.vatPercentage, rmaOrderDataItem.vatPercentage) &&
        Objects.equals(this.vatInaccurate, rmaOrderDataItem.vatInaccurate) &&
        Objects.equals(this.vatCalculated, rmaOrderDataItem.vatCalculated) &&
        Objects.equals(this.productName, rmaOrderDataItem.productName) &&
        Objects.equals(this.productCode, rmaOrderDataItem.productCode) &&
        Objects.equals(this.productSku, rmaOrderDataItem.productSku) &&
        Objects.equals(this.productOptions, rmaOrderDataItem.productOptions) &&
        Objects.equals(this.productImg, rmaOrderDataItem.productImg) &&
        Objects.equals(this.productData, rmaOrderDataItem.productData) &&
        Objects.equals(this.shipmentInfoReference, rmaOrderDataItem.shipmentInfoReference) &&
        Objects.equals(this.promotionGrn, rmaOrderDataItem.promotionGrn) &&
        Objects.equals(this.productIsVirtual, rmaOrderDataItem.productIsVirtual)&&
        Objects.equals(this.additionalProperties, rmaOrderDataItem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, productGrn, qtyOrdered, qtyCommitted, qtyShipped, unitSalePrice, unitListPrice, unitVatAmount, rowSalePrice, rowListPrice, rowVatAmount, vatPercentage, vatInaccurate, vatCalculated, productName, productCode, productSku, productOptions, productImg, productData, shipmentInfoReference, promotionGrn, productIsVirtual, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RmaOrderDataItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productGrn: ").append(toIndentedString(productGrn)).append("\n");
    sb.append("    qtyOrdered: ").append(toIndentedString(qtyOrdered)).append("\n");
    sb.append("    qtyCommitted: ").append(toIndentedString(qtyCommitted)).append("\n");
    sb.append("    qtyShipped: ").append(toIndentedString(qtyShipped)).append("\n");
    sb.append("    unitSalePrice: ").append(toIndentedString(unitSalePrice)).append("\n");
    sb.append("    unitListPrice: ").append(toIndentedString(unitListPrice)).append("\n");
    sb.append("    unitVatAmount: ").append(toIndentedString(unitVatAmount)).append("\n");
    sb.append("    rowSalePrice: ").append(toIndentedString(rowSalePrice)).append("\n");
    sb.append("    rowListPrice: ").append(toIndentedString(rowListPrice)).append("\n");
    sb.append("    rowVatAmount: ").append(toIndentedString(rowVatAmount)).append("\n");
    sb.append("    vatPercentage: ").append(toIndentedString(vatPercentage)).append("\n");
    sb.append("    vatInaccurate: ").append(toIndentedString(vatInaccurate)).append("\n");
    sb.append("    vatCalculated: ").append(toIndentedString(vatCalculated)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    productSku: ").append(toIndentedString(productSku)).append("\n");
    sb.append("    productOptions: ").append(toIndentedString(productOptions)).append("\n");
    sb.append("    productImg: ").append(toIndentedString(productImg)).append("\n");
    sb.append("    productData: ").append(toIndentedString(productData)).append("\n");
    sb.append("    shipmentInfoReference: ").append(toIndentedString(shipmentInfoReference)).append("\n");
    sb.append("    promotionGrn: ").append(toIndentedString(promotionGrn)).append("\n");
    sb.append("    productIsVirtual: ").append(toIndentedString(productIsVirtual)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("productGrn");
    openapiFields.add("qtyOrdered");
    openapiFields.add("qtyCommitted");
    openapiFields.add("qtyShipped");
    openapiFields.add("unitSalePrice");
    openapiFields.add("unitListPrice");
    openapiFields.add("unitVatAmount");
    openapiFields.add("rowSalePrice");
    openapiFields.add("rowListPrice");
    openapiFields.add("rowVatAmount");
    openapiFields.add("vatPercentage");
    openapiFields.add("vatInaccurate");
    openapiFields.add("vatCalculated");
    openapiFields.add("productName");
    openapiFields.add("productCode");
    openapiFields.add("productSku");
    openapiFields.add("productOptions");
    openapiFields.add("productImg");
    openapiFields.add("productData");
    openapiFields.add("shipmentInfoReference");
    openapiFields.add("promotionGrn");
    openapiFields.add("productIsVirtual");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RmaOrderDataItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RmaOrderDataItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RmaOrderDataItem is not found in the empty JSON string", RmaOrderDataItem.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("productGrn") != null && !jsonObj.get("productGrn").isJsonNull()) && !jsonObj.get("productGrn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productGrn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productGrn").toString()));
      }
      // validate the optional field `unitSalePrice`
      if (jsonObj.get("unitSalePrice") != null && !jsonObj.get("unitSalePrice").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("unitSalePrice"));
      }
      // validate the optional field `unitListPrice`
      if (jsonObj.get("unitListPrice") != null && !jsonObj.get("unitListPrice").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("unitListPrice"));
      }
      // validate the optional field `unitVatAmount`
      if (jsonObj.get("unitVatAmount") != null && !jsonObj.get("unitVatAmount").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("unitVatAmount"));
      }
      // validate the optional field `rowSalePrice`
      if (jsonObj.get("rowSalePrice") != null && !jsonObj.get("rowSalePrice").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("rowSalePrice"));
      }
      // validate the optional field `rowListPrice`
      if (jsonObj.get("rowListPrice") != null && !jsonObj.get("rowListPrice").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("rowListPrice"));
      }
      // validate the optional field `rowVatAmount`
      if (jsonObj.get("rowVatAmount") != null && !jsonObj.get("rowVatAmount").isJsonNull()) {
        RmaMoney.validateJsonElement(jsonObj.get("rowVatAmount"));
      }
      if ((jsonObj.get("productName") != null && !jsonObj.get("productName").isJsonNull()) && !jsonObj.get("productName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productName").toString()));
      }
      if ((jsonObj.get("productCode") != null && !jsonObj.get("productCode").isJsonNull()) && !jsonObj.get("productCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productCode").toString()));
      }
      if ((jsonObj.get("productSku") != null && !jsonObj.get("productSku").isJsonNull()) && !jsonObj.get("productSku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productSku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productSku").toString()));
      }
      if ((jsonObj.get("productOptions") != null && !jsonObj.get("productOptions").isJsonNull()) && !jsonObj.get("productOptions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productOptions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productOptions").toString()));
      }
      if ((jsonObj.get("productImg") != null && !jsonObj.get("productImg").isJsonNull()) && !jsonObj.get("productImg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productImg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productImg").toString()));
      }
      if ((jsonObj.get("productData") != null && !jsonObj.get("productData").isJsonNull()) && !jsonObj.get("productData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productData").toString()));
      }
      if ((jsonObj.get("shipmentInfoReference") != null && !jsonObj.get("shipmentInfoReference").isJsonNull()) && !jsonObj.get("shipmentInfoReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipmentInfoReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipmentInfoReference").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("promotionGrn") != null && !jsonObj.get("promotionGrn").isJsonNull() && !jsonObj.get("promotionGrn").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `promotionGrn` to be an array in the JSON string but got `%s`", jsonObj.get("promotionGrn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RmaOrderDataItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RmaOrderDataItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RmaOrderDataItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RmaOrderDataItem.class));

       return (TypeAdapter<T>) new TypeAdapter<RmaOrderDataItem>() {
           @Override
           public void write(JsonWriter out, RmaOrderDataItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RmaOrderDataItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RmaOrderDataItem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RmaOrderDataItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RmaOrderDataItem
   * @throws IOException if the JSON string is invalid with respect to RmaOrderDataItem
   */
  public static RmaOrderDataItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RmaOrderDataItem.class);
  }

  /**
   * Convert an instance of RmaOrderDataItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

