/*
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets rmaRefundMethod
 */
@JsonAdapter(RmaRefundMethod.Adapter.class)
public enum RmaRefundMethod {
  
  UNKNOWN("REFUND_METHOD_UNKNOWN"),
  
  OFFLINE("REFUND_METHOD_OFFLINE"),
  
  COUPON("REFUND_METHOD_COUPON"),
  
  SAME_AS_PAYMENT("REFUND_METHOD_SAME_AS_PAYMENT");

  private String value;

  RmaRefundMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RmaRefundMethod fromValue(String value) {
    for (RmaRefundMethod b : RmaRefundMethod.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RmaRefundMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final RmaRefundMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RmaRefundMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RmaRefundMethod.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RmaRefundMethod.fromValue(value);
  }
}

